use user01;

CREATE TABLE `NOTICE` (
	`BOARD_NUM`	BIGINT	NOT NULL,
	`BOARD_TITLE`	VARCHAR(255)	NULL,
	`BOARD_CONTENTS`	LONGTEXT	NULL,
	`BOARD_WRITER`	VARCHAR(255)	NULL,
	`BOARD_DATE`	DATETIME	NULL,
	`BOARD_HIT`	BIGINT	NULL
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

ALTER TABLE `NOTICE` ADD CONSTRAINT `PK_NOTICE` PRIMARY KEY (
	`BOARD_NUM`
);

ALTER TABLE `NOTICE` MODIFY `BOARD_NUM` INT NOT NULL AUTO_INCREMENT;

show databases;

